---
- hosts: all
  tasks:
   - name: uninstall nvidia using installer
     become: true
     command: "nvidia-installer --uninstall --silent"
     failed_when: false
   - name: uninstall nvidia and cuda drivers
     become: true
     apt:
       name: ['libnvidia-*', 'nvidia-*', 'cuda-*']
       state: absent
       purge: yes
       force: yes
       autoremove: yes
       autoclean: yes
     failed_when: false
